<template>
  <NavBar></NavBar>
  <Header></Header>
  <HireExpert></HireExpert>
  <TestingServices></TestingServices>
  <User></User>
  <Engineer></Engineer>
  <Audit></Audit>
  <FeatureArticles></FeatureArticles>
  <Contact></Contact>
  <Footer></Footer>
</template>
